[package]
name = "Navi"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo = "0.11.0"
web-sys = { version = "0.3.85", features = ["Storage", "Window"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-hooks = "0.4.0"
